# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
