# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=tinymce.models.HTMLField(),
        ),
    ]
